@baseUrl = http://localhost:3000

# @name create_account

POST {{{{baseUrl}}}}/accounts
Content-Type: application/json

{  
  "name": "Eric",
  "email": "eric3@gmail.com",
  "password": "securepassword123",
}

###

# @name authenticate_user

POST {{{{baseUrl}}}}/sessions
Content-Type: application/json

{
  "email": "eric3@gmail.com",
  "password": "securepassword123",
}